api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /traefik/dynamic.yml

certificatesResolvers:
  myresolver:
    acme:
      email: ${TRAEFIK_EMAIL}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
